import { RedCallout, SlideTitle } from '../components/core';
import { ALTERNATION } from '../data/facts';

export function S14Alternation() {
  return (
    <>
      <SlideTitle lede="A synthetic day is generated by cycling two specialist models end-to-end.">
        The alternating pipeline
      </SlideTitle>

      <div className="flex items-stretch gap-2">
        {ALTERNATION.phases.map((p, i) => (
          <div key={i} className="flex flex-1 items-center gap-2">
            <div
              className={`flex w-full flex-col rounded-lg p-4 text-white shadow-sm ${
                p.model === 'exchange' ? 'bg-teal' : 'bg-navy'
              }`}
            >
              <span className="font-mono text-[10.5px] tracking-[0.13em] uppercase opacity-80">
                {p.label}
              </span>
              <span className="font-display mt-1 text-[18px] leading-tight font-bold">{p.sub}</span>
              <span className="mt-1.5 font-mono text-[12px] opacity-90">{p.detail}</span>
            </div>
            {i < ALTERNATION.phases.length - 1 && (
              <div className="flex shrink-0 flex-col items-center">
                <svg width="22" height="14" viewBox="0 0 22 14" aria-hidden>
                  <path d="M0 7h17m0 0l-5-5m5 5l-5 5" stroke="#6B7B7B" strokeWidth="1.8" fill="none" />
                </svg>
                <span className="mt-0.5 font-mono text-[9.5px] text-muted">
                  {i % 2 === 0 ? 'T:100' : 'T:104'}
                </span>
              </div>
            )}
          </div>
        ))}
      </div>

      <div className="mt-6 grid flex-1 grid-cols-[1.2fr_1fr] items-start gap-6">
        <div className="rounded-lg bg-surface p-5">
          <div className="font-mono text-[11.5px] tracking-[0.13em] text-teal-ink uppercase">
            Conditioning inputs — per model call
          </div>
          <div className="mt-3 grid grid-cols-2 gap-x-6 gap-y-2">
            {ALTERNATION.conditioning.map((c) => (
              <div key={c} className="flex gap-2.5 text-[15px] text-ink/85">
                <span className="mt-[9px] h-1 w-3 shrink-0 rounded bg-teal" />
                {c}
              </div>
            ))}
          </div>
        </div>
        <div className="rounded-lg border border-mist p-5">
          <div className="font-mono text-[11.5px] tracking-[0.13em] text-navy uppercase">Output</div>
          <p className="mt-2.5 text-[15.5px] leading-snug text-ink">{ALTERNATION.output}</p>
          <p className="mt-2 font-mono text-[12px] text-muted">{ALTERNATION.handoffs}</p>
        </div>
      </div>

      <RedCallout>
        One model cannot do this — patient exchange and scanning are different processes, and the
        alternation <em>is</em> the architecture.
      </RedCallout>
    </>
  );
}
