@echo off
REM Complete pipeline to regenerate sequences with all fixes and run evaluation
REM Author: Generated by Claude Code
REM Date: 2025-11-10

echo ======================================================================
echo COMPLETE PXCHANGE PIPELINE WITH FIXES
echo ======================================================================
echo.

echo Step 1: Generate sequences with fixed code (15 samples per customer)
echo ----------------------------------------------------------------------
python main_pipeline.py generate --num-samples-per-customer 15

echo.
echo Step 2: Run evaluation on generated sequences
echo ----------------------------------------------------------------------
python main_pipeline.py evaluate --generated-file generated_sequences.csv

echo.
echo ======================================================================
echo PIPELINE COMPLETE
echo ======================================================================
echo.
echo Generated file: outputs\generated_sequences.csv
echo.
echo Modifications included:
echo   - Fixed MRI_MSR_104 repetition issue (now averages 1.2 per sequence)
echo   - Added BodyGroup_from and BodyGroup_to columns
echo   - Added unique PatientID_from and PatientID_to for each sample
echo.
pause
